import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cn from 'classnames';
import './globals.scss'
import styles from './layout.module.scss'
import Link from 'next/link'
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Rick and Morty</title>
      </Head>
      <body className={cn(inter.className, styles.body)}>
        <nav className={styles.navBar}>
          <Link href={'/'}>Main</Link>
          <Link href={'/characters'}>Characters</Link>
          <Link href={'/locations'}>Locations</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
